### ISSUE TITLE
Confusion over the Park's correction for vibrational relaxtion

### ISSUE THREAD

**Issue by WallyMaier** [mutationpp/Mutationpp#171] opened 2021-07-29 15:57 UTC
Hi All, 

I had a quick question regarding Park's correction within Mutation++.   Particularly in the computation of the collision speed(s), Cs.  In the literature, Cs is computed using :  `sqrt(8*R*T/(pi*Ms))`  (sorry, my images weren't loading in properly.) Here, we can see the use of MolarMass in the denominator

However Mutation++ uses a reduced mass, mu, which is (Ms_i*Ms_j/(Ms_i+Ms_j)).   I was hoping there was some literature that discusses the use here.  

I am working on SU2-NEMO and found that these differences account for results being slightly different than LeMANS.  

Thanks for the help!

**Comment by jbscoggi** [comment] 2021-07-29 21:34
Hey @WallyMaier, thanks for your question.  For clarity for others coming to this question, we are talking about this: https://github.com/mutationpp/Mutationpp/blob/8c1c129474239dc172d42ed82310a108aa7bba42/src/transfer/OmegaVT.cpp#L154-L168

Indeed, based on the literature it seems the common approach is to use the species mass (or molecular weight depending on R or kB) and not the reduced mass. For example, the Gnoffo et al. (1989) classic paper uses species mass.

@grgbellas, I think this was implemented by you?  Can you confirm? and if so, could you provide a reference for the way you have implemented it?

**Comment by grgbellasvki** [comment] 2021-07-30 05:58
Hello @WallyMaier,

Thanks for bringing this to our attention.

If I remember correctly it comes from some legacy version of the original mutation library. I will try to retrieve it and see if there is any comment on why this formalism was chosen. 

In any case, we should probably stick to literature for a term like this one and follow the Gnoffo's (1989) approach. What's your opinion @jbscoggi?

**Comment by jbscoggi** [comment] 2021-07-30 07:21
Yep, totally agree we should stick to the literature for this and that Gnoffo's approach is the one to follow.  I'll work on it as soon as I can and submit a PR when it's done.

**Comment by jbscoggi** [comment] 2021-08-04 09:46
Hi @WallyMaier and @grgbellasvki, I have just submitted a PR to fix this issue.  Once the reviews and tests are done, I'll merge and hopefully this will fix the problem.

**Comment by jbscoggi** [comment] 2021-08-10 08:33
Hey @WallyMaier, I believe the problem is now fixed.  Can you please reinstall M++ on your end and verify that the comparison with LeMANS is working?

**Comment by WallyMaier** [comment] 2021-08-10 17:56
@jbscoggi Sounds good!  Will report back soon.

**Comment by jbscoggi** [comment] 2021-11-08 16:57
Hey @WallyMaier, any update about the update to the OmegaVT term?

**Comment by WallyMaier** [comment] 2021-11-08 17:40
@jbscoggi Sorry JB,  Let me do this right now!

**Comment by WallyMaier** [comment] 2021-11-09 17:44
Heres a quick update....running the same case for N2-N case the thermal relaxation behavior can be seen here:
![N2-tt-tv](https://user-images.githubusercontent.com/17651188/140976691-fd4fdf0e-f9d9-4f22-8055-957b4de26a82.png)

Something isnt working as expected,

**Comment by mgoodson-cvd** [comment] 2022-01-24 14:33
I can further confirm that the modifications made in c9a924fde43216e0777a918dc5042eaa18ae98b5 appear to be problematic. @jbscoggi I can't post these results here, but I would be happy to share more in private communication. Suffice it to say that we are running two-temperatures with Mutation++ and comparing against a well-established and trusted CFD code. Our results prior to this commit match very well and our results after this commit do not.

**Comment by mgoodson-cvd** [comment] 2022-01-31 20:43
After bisecting the commits between a known good version and the latest master, I can confirm that https://github.com/mutationpp/Mutationpp/commit/bc9ce81c5dc607f927fc4e07781b8bad44e43d6c is the breaking commit. I will start digging in to see where the bug was introduced.

**Comment by mgoodson-cvd** [comment] 2022-02-01 21:10
@jbscoggi @WallyMaier I believe I have found the bug. The Park correction to the Landau-Teller relaxation time is missing the temperature scaling factor [here](https://github.com/mutationpp/Mutationpp/blob/b7cfe9c556a5a644b9c08d36624cf3e47a9d30bb/src/transfer/MillikanWhite.cpp#L146),
```math
\sigma_s = \sigma_{s,0} \left ( \frac{50000}{T} \right )^2
```
This was present prior to bc9ce81, as can be seen [here](https://github.com/mutationpp/Mutationpp/blob/8c1c129474239dc172d42ed82310a108aa7bba42/src/transfer/OmegaVT.cpp#L160-165). Once I make this fix, my results match both the comparison code and the older results much better.

I'll make a pull request with the fix. @jbscoggi should I include the limiting temperature of 20,000 K in there? I've seen varying values or none at all.

**Comment by WallyMaier** [comment] 2022-02-02 00:51
@mgoodson-cvd Thanks for looking into this!  Ill try to run the case above again with your fixes, and iIl post the results here.

**Closed** 2022-02-15 03:26 UTC
